omap: remoteproc: fix a compilation error on autosuspend disable
The patch,
"omap: remoteproc: set the load boot address in activate function",
introduced a compilation error when the remoteproc autosuspend is
disabled from the kernel menuconfig.

drivers/remoteproc/omap_remoteproc.c: In function 'omap_rproc_activate':
drivers/remoteproc/omap_remoteproc.c:191: error: 'struct omap_rproc_priv' has no member named 'bootaddr'
drivers/remoteproc/omap_remoteproc.c: In function 'omap_rproc_start':
drivers/remoteproc/omap_remoteproc.c:470: error: 'struct omap_rproc_priv' has no member named 'bootaddr'
make[2]: *** [drivers/remoteproc/omap_remoteproc.o] Error 1
make[1]: *** [drivers/remoteproc] Error 2
make: *** [drivers] Error 2

The same has been fixed.

Change-Id: I99506d6d30724e51a0325762d9ba2dff533fe852
Reported-by: Mihail Dobrev <x0099086@ti.com>
Signed-off-by: Miguel Vadillo <vadillo@ti.com>